name: mvvm_arch
description: Flutter MVVM Architecture, create MVVM Pattern to your project structure. Providing Controller-View-ViewModel with LiveData
version: 1.0.0
author: Tanapoj Chaivanichanan <tanapoj@centrilliontech.co.th>
homepage: https://github.com/nartra/flutter_mvvm_arch

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: '>=1.12.1'

dependencies:
  flutter:
    sdk: flutter
  async: ^2.4.0
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: